kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-volume
  labels:
    type: local
    app: mapserver
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/nginx"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-pv-claim
  labels:
    app: mapserver
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mapserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mapserver
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          command: ["nginx", "-c", "/config/nginx/nginx.conf", "-g", "daemon off;"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /config/nginx
            - name: mapserver
              mountPath: /etc/nginx/html
      volumes:
        - name: mapserver
          persistentVolumeClaim:
            claimName: nginx-pv-claim
        - name: nginx-conf
          configMap:
            name: mapserver-config
            items:
              - key: nginx-config
                path: nginx.conf
