kind: PersistentVolume
apiVersion: v1
metadata:
  name: skosmos-volume
  labels:
    type: local
    # io.kompose.service: skosmos
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/tom/src/k8s/skosmos/config/config-k8s.ttl"
