apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
     nginx.ingress.kubernetes.io/proxy-body-size: "0"
     nginx.ingress.kubernetes.io/whitelist-source-range:
       #10.0.0.0/8,172.16.0.0/12,127.0.0.1/32,80.100.161.180/32,::1/128
       10.152.183.0/24,172.16.0.0/12,80.100.161.180/32,13.95.28.63/32
  name: fuseki-ingress
spec:
   tls:
   - hosts:
     - fuseki.v7f.eu
     secretName: testsecret-tls
   rules:
   - host: fuseki.v7f.eu
     http:
       paths:
       - pathType: Prefix
         path: /
         backend:
           service:
             name: fuseki
             port:
               number: 9030
