apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
   tls:
   - hosts:
     - tom-kad-k8s.westeurope.cloudapp.azure.com
     secretName: testsecret-tls
   rules:
   - host: tom-kad-k8s.westeurope.cloudapp.azure.com
     host: k8s.v7f.eu
     http:
       paths:
       - path: /
         backend:
           serviceName: pythonapp
           servicePort: 80
