PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX spatialF: <http://jena.apache.org/spatial#>
PREFIX units: <http://www.opengis.net/def/uom/OGC/1.0/>

SELECT * # ?s2 # ?s2 ?s1
WHERE { 
	?s2 <http://pand/area> ?o3 .
	FILTER(?o3 > 1000) .  
} 
