[package]
name = "rqs"
version = "0.1.0"
authors = ["Tom Vijlbrief <tvijlbrief@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.17.5"
rand = "0.7.3"
