kind: PersistentVolume
apiVersion: v1
metadata:
  name: pythonapp-volume
  labels:
    type: local
    app: pythonapp
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/pythonapp"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pythonapp-pv-claim
  labels:
    app: pythonapp
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
  labels:
    app: pythonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
        - name: pythonapp
          image: tomtor/test-k8s:hello-0.20
          # imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: pythonapp-config
          volumeMounts:
            - mountPath: /data
              name: pythonapp
      volumes:
        - name: pythonapp
          persistentVolumeClaim:
            claimName: pythonapp-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: pythonapp
  labels:
    app: pythonapp
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: pythonapp
