kind: PersistentVolume
apiVersion: v1
metadata:
  name: pgadmin-volume
  labels:
    type: local
    app: pgadmin4
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/pgadmin"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgadmin4-pv-claim
  labels:
    app: pgadmin4
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4
  labels:
    app: pgadmin4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin4
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      containers:
        - name: pgadmin4
          #image: dpage/pgadmin4:4.4
          #image: dpage/pgadmin4:4.19
          #image: dpage/pgadmin4:4.26
          image: dpage/pgadmin4:6.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: pgadmin4-config
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: pgadmin-volume
      volumes:
        - name: pgadmin-volume
          persistentVolumeClaim:
            #claimName: myclaim
            claimName: pgadmin4-pv-claim
