kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pvbt12-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/pg/pg12.0beta"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres12-0-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
#---
#kind: PersistentVolume
#apiVersion: v1
#metadata:
#  name: postgrestemp-pv-volume
#  labels:
#    type: local
#    app: postgres
#spec:
#  storageClassName: manual
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteMany
#  hostPath:
#    path: "/mnt/postgres"
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: postgrestemp-pv-claim
#  labels:
#    app: postgres
#spec:
#  storageClassName: manual
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 5Gi
